-- Convertir las columnas al tipo de dato MONEY de forma segura
ALTER TABLE CATEGORIAS ALTER COLUMN Sueldo TYPE MONEY;
ALTER TABLE CUENTAS ALTER COLUMN Saldo TYPE MONEY;
ALTER TABLE MOVIMIENTOS ALTER COLUMN Monto TYPE MONEY;